using System;
using System.IO;
using System.Reflection;
using TMPro;
using UnityEditor;
using UnityEngine;

namespace FalsePositive.Editor
{
    /// <summary>
    /// TMP Essential Resources have never been imported into this project — no
    /// Assets/TextMesh Pro/ folder, no font assets anywhere, even though the
    /// TMPro package code itself is already present via com.unity.ugui. The
    /// public path (Window > TextMeshPro > Import TMP Essential Resources) is a
    /// menu item a human clicks; this project's scenes are instead generated by
    /// ProjectBootstrapBuilder.cs via -batchmode -executeMethod, so the import
    /// has to happen the same way. Kept as its own menu item / batch invocation
    /// rather than folded into BuildEverything from the start — the asset
    /// import is worth isolating from scene building on the first run so a
    /// failure here is unambiguous, not buried in a longer log.
    ///
    /// Deliberately never touches TMP_Settings.instance / TMP_Settings.defaultFontAsset
    /// (the static singleton accessor): in the Editor, that getter's first call
    /// can schedule TMP_PackageResourceImporterWindow to open itself a second
    /// later (TMP_Settings.cs, DelayShowPackageImporterWindow) — an interactive
    /// window with nothing to drive it in -batchmode -nographics. Every check
    /// here goes through AssetDatabase.LoadAssetAtPath + SerializedObject on
    /// that specific asset instead, which has no such side effect.
    /// </summary>
    public static class TmpEssentialsBootstrap
    {
        private const string EssentialsPackageRelativePath = "Package Resources/TMP Essential Resources.unitypackage";
        private const string SettingsAssetPath = "Assets/TextMesh Pro/Resources/TMP Settings.asset";
        private const string DefaultFontFieldName = "m_defaultFontAsset";

        [MenuItem("Tools/False Positive/Bootstrap/0 - Import TMP Essentials")]
        public static void ImportTmpEssentials()
        {
            if (TryGetDefaultFont(out _))
            {
                Debug.Log("[TmpEssentialsBootstrap] TMP Essential Resources already imported — nothing to do.");
                return;
            }

            string packagePath = FindEssentialsPackagePath();
            if (packagePath == null)
            {
                Fail("Could not locate 'TMP Essential Resources.unitypackage' under Library/PackageCache/com.unity.ugui* " +
                    "— is com.unity.ugui installed? Check Packages/manifest.json.");
                return;
            }

            if (!TryImport(packagePath))
            {
                Fail("Every import path failed (public ImportPackage + two reflection fallbacks). Open the Editor " +
                    "once and run Window > TextMeshPro > Import TMP Essential Resources manually, then re-run " +
                    "scene generation.");
                return;
            }

            Debug.Log(TryGetDefaultFont(out TMP_FontAsset font)
                ? $"[TmpEssentialsBootstrap] TMP Essential Resources imported. Default font: {font.name}"
                : "[TmpEssentialsBootstrap] Import reported success but no default font is set — check manually.");
        }

        /// <summary>Loud gate every scene builder that places TMP text must call
        /// first — a scene built with a null font renders invisible text, which
        /// reads as a layout bug and costs an hour to track down.</summary>
        public static TMP_FontAsset RequireDefaultFont()
        {
            if (!TryGetDefaultFont(out TMP_FontAsset font))
            {
                throw new InvalidOperationException(
                    "[TmpEssentialsBootstrap] TMP Essential Resources are not imported (no default font asset at " +
                    SettingsAssetPath + "). Run 'Tools/False Positive/Bootstrap/0 - Import TMP Essentials' first.");
            }
            return font;
        }

        private static bool TryGetDefaultFont(out TMP_FontAsset font)
        {
            font = null;
            AssetDatabase.Refresh();
            TMP_Settings settings = AssetDatabase.LoadAssetAtPath<TMP_Settings>(SettingsAssetPath);
            if (settings == null) return false;

            SerializedObject serialized = new SerializedObject(settings);
            SerializedProperty fontProperty = serialized.FindProperty(DefaultFontFieldName);
            font = fontProperty?.objectReferenceValue as TMP_FontAsset;
            return font != null;
        }

        private static string FindEssentialsPackagePath()
        {
            UnityEditor.PackageManager.PackageInfo info =
                UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(TMP_Settings).Assembly);
            if (info == null) return null;

            string path = Path.Combine(info.resolvedPath, EssentialsPackageRelativePath);
            return File.Exists(path) ? path : null;
        }

        private static bool TryImport(string packagePath)
        {
            // 1. Public, documented API. interactive:false imports every item
            // immediately with no dialog shown at all (the dialog only appears
            // when interactive:true) — this is the standard headless-import path
            // and needs no reflection, so it goes first.
            try
            {
                AssetDatabase.ImportPackage(packagePath, false);
                if (TryGetDefaultFont(out _)) return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[TmpEssentialsBootstrap] AssetDatabase.ImportPackage(interactive:false) threw: {e.Message}");
            }

            // 2. Internal AssetDatabase.ImportPackageImmediately(string) — symbol
            // confirmed present in 6000.5.6f1's UnityEditor.dll. Undocumented and
            // could change signature across versions, so it's a fallback, not the
            // primary path.
            if (TryInvokeStaticStringMethod(typeof(AssetDatabase), "ImportPackageImmediately", packagePath)
                && TryGetDefaultFont(out _))
                return true;

            // 3. UnityEditor.PackageUtility.ImportPackageAssetsImmediately — also
            // present, also undocumented, last resort before giving up.
            Type packageUtilityType = Type.GetType("UnityEditor.PackageUtility, UnityEditor");
            if (packageUtilityType != null
                && TryInvokeStaticStringMethod(packageUtilityType, "ImportPackageAssetsImmediately", packagePath)
                && TryGetDefaultFont(out _))
                return true;

            return false;
        }

        private static bool TryInvokeStaticStringMethod(Type type, string methodName, string arg)
        {
            try
            {
                MethodInfo method = type.GetMethod(methodName,
                    BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic,
                    null, new[] { typeof(string) }, null);
                if (method == null) return false;
                method.Invoke(null, new object[] { arg });
                return true;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[TmpEssentialsBootstrap] Reflection call to {type.Name}.{methodName} failed: {e.Message}");
                return false;
            }
        }

        private static void Fail(string message)
        {
            Debug.LogError("[TmpEssentialsBootstrap] " + message);
            if (Application.isBatchMode) EditorApplication.Exit(2);
        }
    }
}
